# Generated by Django 5.1.5 on 2025-09-13 07:39

import artworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.IntegerField(default=artworks.models.get_next_artwork_id, primary_key=True, serialize=False),
        ),
    ]
