# Generated by Django 5.1.5 on 2025-09-13 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='location',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_exhibitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
