name: Deploy to EC2 on Main Merge

on:
  push:
    branches:
      - main  # ✅ main 브랜치에 push 될 때만 실행

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/artrip-backend
            git pull origin main
            docker-compose down
            docker-compose up --build -d

